### ISSUE TITLE
How to use $sort ,$limit  in my EL query ?

### ISSUE THREAD

**Issue by iamvasim786** [boubaks/elasticsearch-query#1]
My Query Object look like  =>
`var query = {
        'verified': true,
        '$sort': {"@timestamp":"desc"}
        '$lte': { 'salary': 2000 },
        '$gte': { 'salary': 1000 }
    };`
how to use handler for generating above query.

**Comment by iamvasim786** [comment]
@boubaks 
please reply.

**Comment by boubaks** [comment]
Hello @iamvasim786 :) Sorry for answer late.

I saw an issue on the $sort. I will fix it now 👍

**Comment by boubaks** [comment]
I fixed it @iamvasim786 :-)
For the $sort you can now use it 👍 

`var complexQuery = {
	'verified': true,
	'$exist': 'age',
	'$lte': { 'age': 60 },
	'$gte': { 'age': 18 },
	'$sort': { 'timestamp': -1 },
	'!username': 'kimchy',
	'$facet': 'username',
	'$count': true
};
`

About the $limit you have to set up on the options before you make your request (by size & from options), you can't use it directly on the elasticsearch-query generator.
You can use the $limit only if you're using the $facet (simple aggregation) which will be done on it.

Hope I helped you. I you have any questions I'm available ;)
