### ISSUE TITLE
How to generate multiple range query ?

### ISSUE THREAD

**Issue by iamvasim786** [boubaks/elasticsearch-query#2]
I have two query object which one is correct in multiple range query case.
`var complexQuery1 = {
        '$lte': { 'age': 60 },
        '$gte': { 'age': 18 },
        '$lte': { 'date': 100060 },
        '$gte': { 'date': 200000 }
};
`
`var complexQuery2 = {
        '$lte': { 'age': 60,'date': 100060 },
        '$gte': { 'age': 18,'date': 200000  }
};
`
I think both will create wrong ES query . please explain.
It has been generated in single range object - like
`{"range":{"age":{"lte":60,"gte":18}},{"date":{"lte":100060,"gte":200000}}}`

**Comment by iamvasim786** [comment]
Generated ES query should like - two different range
`{
    "query": {
        "bool": {
            "must": [
                {
                    "range": {
                        "created_at": {
                            "gte": "2013-12-09T00:00:00.000Z"
                        }
                    }
                },
                {
                    "range": {
                        "happens_on": {
                            "lte": "2013-12-16T00:00:00.000Z"
                        }
                    }
                }
            ]
        }
    }
}
'`

**Comment by iamvasim786** [comment]
@boubaks 
please reply.

**Comment by boubaks** [comment]
Hello @iamvasim786 
Right in the first complexQuery1 I didn't manage this type of query, that will only take the last field and here is `date`

The complexQuery2 is the good way to use the multiple range query case in my elasticsearch-query.

I didn't understand your second message. A correct multiple range elasticsearch query is with different range field ?

**Comment by iamvasim786** [comment]
for complexQuery2 , ES query should be -

{ "range": { "age": { "gte": 10,"lte":20} } }, { "range": { "date": { "gte": 10202002,"lte":30202002 } } } 

while your generate ES query like -

{"range":{"age":{"lte":60,"gte":18}},{"date":{"lte":100060,"gte":200000}}}

**Comment by iamvasim786** [comment]
one more question , can update your code according to latest ES,
because in ES 5.x, filtered : {filter:{....}} has been deprecated.
please update..

**Comment by iamvasim786** [comment]
@boubaks 
please check..

**Comment by boubaks** [comment]
I will check that this week @iamvasim786 👍

**Comment by boubaks** [comment]
Hello @iamvasim786 :)

I worked on it ! It's normally now great with ELS 5.X (and multiple range), Enjoy :)

If you have any problems or feature you need into tell me 👍

**Comment by iamvasim786** [comment]
thanks @boubaks

**Comment by iamvasim786** [comment]
Hi @boubaks 

It is possible to generate generalize search query i.e search with different different criteria like term,wildcard,match_phrase etc.
ELS Query like -

` ==> queryELS
  {
    "query": {
      "bool":{
        "must":[
          {
            "term":{
              "createdBy":"kimchy"
            },
           "wildcard":{
              "userName":"*vasim*"
            }
          }
        ],
        "must_not":[],
        "should":[],
        "filter":[]
      }
    }
  }
  <== `

**Comment by boubaks** [comment]
Hello @iamvasim786 
You can add handle to manage thoses new features and be flexible :) 
```
  /*
  ** @query: {$test: "elasticsearch"}
  ** @queryELS: the query generate for elasticsearch
  ** callback: function(err, queryELS)
  */ 
  var handleWildcard = function (query, queryELS, callback) {
    var error = null;
    if (query.$wildcard) {
      var must = queryELS.query.bool.must ? queryELS.query.bool.must : [];
      must.push({"wildcard": query.$wildcard});
    }
    callback(error, queryELS);
  };

  elsQueryGenerator.addHandle('$wildcard', null, handleWildcard);
```

Hope this helped you 👍
